version: "3.4"

services:

  eurekalabs_api:
    build: ./
    command:
      [ "sh", "-c", " uvicorn main:app --reload --workers 2 --host 0.0.0.0 --port 8000" ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
